# Generated by Django 4.2.2 on 2023-08-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_garticbread', '0002_advertisement_user_alter_advertisement_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(default=1, upload_to='advertisements/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
